# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hbr0wfumJHMcSlPfbeCM8kAeHYnWR58y
"""

import numpy as np
import matplotlib.pyplot as plt

# Sinus funksiyasi grafigi
x = np.linspace(0, 10, 100)  # X qiymatlari
y = np.sin(x)  # Y qiymatlari (sinus)

plt.figure(figsize=(10, 5))

# Sinus funksiyasi grafigi
plt.subplot(1, 2, 1)
plt.plot(x, y, label="Sinus(x)", color="blue")
plt.title("Sinus Funksiyasining Grafigi")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid()

# Tasodifiy nuqtalar scatter grafigi
x_random = np.random.uniform(0, 10, 50)  # X uchun tasodifiy qiymatlar
y_random = np.random.uniform(0, 10, 50)  # Y uchun tasodifiy qiymatlar

plt.subplot(1, 2, 2)
plt.scatter(x_random, y_random, color="blue", label="Nuqtalar")
plt.title("Tasodifiy Nuqtalar Scatter Grafigi")
plt.xlabel("X qiymatlari")
plt.ylabel("Y qiymatlari")
plt.legend()
plt.grid()

plt.tight_layout()
plt.show()